In [1]:
from mxnet import nd
x = nd.arange(12)
print(x)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>


In [4]:
x.shape
x.size

12

In [6]:
y = x.reshape(3, 4)
print(y)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>


In [9]:
y.reshape((-1, 4))
print(y)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>


reshape中填写-1，可以根据其他维度推断

In [7]:
z = nd.zeros((2, 3, 4))
print(z)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>


In [10]:
m = nd.ones((3, 4))
print(m)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>


In [11]:
n = nd.random.normal(0, 1, shape = (3, 4))
print(n)


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>


期望为0，标准差为1的正太分布，可用nd.random.normal生成，参数分别是期望，标准差和形状