In [1]:
from mxnet import nd
x = nd.arange(12)
print(x)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>


In [4]:
x.shape
x.size

12

In [6]:
y = x.reshape(3, 4)
print(y)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>


In [9]:
y.reshape((-1, 4))
print(y)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>


reshape中填写-1，可以根据其他维度推断

In [7]:
z = nd.zeros((2, 3, 4))
print(z)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>


In [10]:
m = nd.ones((3, 4))
print(m)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>


In [11]:
n = nd.random.normal(0, 1, shape = (3, 4))
print(n)


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>


期望为0，标准差为1的正太分布，可用nd.random.normal生成，参数分别是期望，标准差和形状

In [5]:
x = nd.array([1, 2, 3])
y = nd.array([3, 4, 5])

In [6]:
nd.dot(x, y.T)


[26.]
<NDArray 1 @cpu(0)>

In [7]:
nd.concat(x, y, dim = 0)


[1. 2. 3. 3. 4. 5.]
<NDArray 6 @cpu(0)>

In [13]:
x1 = nd.array([[1, 2, 3]])
y1 = nd.array([[4, 5, 6]])

In [15]:
nd.concat(x1, y1, dim = 0)


[[1. 2. 3.]
 [4. 5. 6.]]
<NDArray 2x3 @cpu(0)>

concat分别在行上和列上连结ndarray，dim=0在行上连结，dim=1在列上连结

In [16]:
s = x1 == y1
print(s)


[[0. 0. 0.]]
<NDArray 1x3 @cpu(0)>


In [17]:
s2 = x1.sum()
print(s2)


[6.]
<NDArray 1 @cpu(0)>


In [19]:
x2 = nd.array([[1, 2, 3],[2, 3, 4]])
x3 = x2[1:2]
x3[0,2] = -1
print(x3)


[[ 2.  3. -1.]]
<NDArray 1x3 @cpu(0)>


In [21]:
x3 = x2
x4 = x2.zeros_like()
before = id(x4)
x4[:] = x2 + x3
id(x4) == before

True

在上例中，如果不用索引，那个将会为x4产生新内存。如果用了索引，就会保存到原来x4的内存了。但是x2+x3还是产生了临时内存。

In [22]:
import numpy as np
x6 = np.ones((2, 3))
x7 = nd.array(x6)
print(x6, x7)

[[1. 1. 1.]
 [1. 1. 1.]] 
[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>


In [24]:
x8 = x7.asnumpy()
print(x8)
x8

[[1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

可以使用asnumpy将ndarray转为numpy中的array